"""empty message

Revision ID: 00ea9d74e11e
Revises: a269d44c047d
Create Date: 2023-03-25 16:18:31.465903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ea9d74e11e'
down_revision = 'a269d44c047d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_upcoming', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('is_upcoming')

    # ### end Alembic commands ###
