"""empty message

Revision ID: 175802ef6cdf
Revises: 6dbedbdaf308
Create Date: 2023-04-12 19:14:46.942307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175802ef6cdf'
down_revision = '6dbedbdaf308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('is_upcoming')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_upcoming', sa.BOOLEAN(), nullable=False))

    op.drop_table('friendship')
    # ### end Alembic commands ###
