"""empty message

Revision ID: 21602a68a9a1
Revises: 54d73d45e6a0
Create Date: 2023-04-14 17:55:56.296507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21602a68a9a1'
down_revision = '54d73d45e6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('iso_date',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('iso_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
