"""empty message

Revision ID: 250a8c907218
Revises: 3209e7593a1c
Create Date: 2023-04-22 20:24:35.485061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250a8c907218'
down_revision = '3209e7593a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_friendship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_friendship',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('pending_friend_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pending_friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'pending_friend_id')
    )
    # ### end Alembic commands ###
