"""empty message

Revision ID: 8794397ab485
Revises: 9a857cbf20e8
Create Date: 2023-04-16 14:15:51.487333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8794397ab485'
down_revision = '9a857cbf20e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_event')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo_link')

    op.create_table('_alembic_tmp_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_hash', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('speaker', sa.VARCHAR(), nullable=True),
    sa.Column('speaker_title', sa.VARCHAR(), nullable=True),
    sa.Column('host', sa.VARCHAR(), nullable=True),
    sa.Column('department', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('time', sa.VARCHAR(), nullable=True),
    sa.Column('iso_date', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_upcoming', sa.BOOLEAN(), nullable=True),
    sa.Column('link', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
