"""empty message

Revision ID: adf4c295a5e8
Revises: 8794397ab485
Create Date: 2023-04-20 22:16:08.414198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf4c295a5e8'
down_revision = '8794397ab485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending__friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pending_friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pending_friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending__friendship')
    # ### end Alembic commands ###
